/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyBookingApp;

/**
 *
 * @author Maxie
 */
public class EkaHotel extends javax.swing.JFrame {

    /**
     * Creates new form BookingApp
     */
    public EkaHotel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        theDate = new javax.swing.JLabel();
        theEvent = new javax.swing.JLabel();
        theTime = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        theCapacity = new javax.swing.JLabel();
        insertTime = new javax.swing.JTextField();
        insertCapacity = new javax.swing.JTextField();
        insertEvent = new javax.swing.JTextField();
        selectNum = new javax.swing.JComboBox();
        theMonth = new javax.swing.JTextField();
        selectMonth = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        selectYear = new javax.swing.JComboBox();
        book = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        theDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        theDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        theDate.setText("DD:");
        getContentPane().add(theDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, 28));

        theEvent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        theEvent.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        theEvent.setText("EVENT:");
        getContentPane().add(theEvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 90, 28));

        theTime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        theTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        theTime.setText("TIME:");
        getContentPane().add(theTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 90, 28));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("EVENT:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 303, 90, 0));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("EVENT:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 313, 90, 0));

        theCapacity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        theCapacity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        theCapacity.setText("CAPACITY:");
        getContentPane().add(theCapacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 90, 28));
        getContentPane().add(insertTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 228, -1));

        insertCapacity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(insertCapacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 228, -1));

        insertEvent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(insertEvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 228, -1));

        selectNum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        selectNum.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(selectNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 35, -1));

        theMonth.setText("MM:");
        getContentPane().add(theMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        selectMonth.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        selectMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "June", "July", "Aug", "Sept", "Oct", "Nov", "Dec" }));
        getContentPane().add(selectMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setText("YY:");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 34, -1));

        selectYear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        selectYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2018", "2019", "2020", "2021", "2022", "2023", "2025" }));
        getContentPane().add(selectYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, -1));

        book.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        book.setText("BOOK");
        book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookActionPerformed(evt);
            }
        });
        getContentPane().add(book, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, -1, -1));

        back.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        back.setText("BACK");
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyBookingApp/eka-hotel-nairobi-5.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 650, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookActionPerformed
    }//GEN-LAST:event_bookActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EkaHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EkaHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EkaHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EkaHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new EkaHotel().setVisible(true);
        });
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton book;
    private javax.swing.JTextField insertCapacity;
    private javax.swing.JTextField insertEvent;
    private javax.swing.JTextField insertTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox selectMonth;
    private javax.swing.JComboBox selectNum;
    private javax.swing.JComboBox selectYear;
    private javax.swing.JLabel theCapacity;
    private javax.swing.JLabel theDate;
    private javax.swing.JLabel theEvent;
    private javax.swing.JTextField theMonth;
    private javax.swing.JLabel theTime;
    // End of variables declaration//GEN-END:variables

    private void valueOfString(Object selectedItem) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
