/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyBookingApp;

/**
 *
 * @author Maxie
 */
public class oleSereni1 extends javax.swing.JFrame {

    /**
     * Creates new form oleSereni1
     */
    public oleSereni1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        insertTime = new javax.swing.JTextField();
        theDate = new javax.swing.JLabel();
        theTime = new javax.swing.JLabel();
        theEvent = new javax.swing.JLabel();
        theCapacity = new javax.swing.JLabel();
        theMonth = new javax.swing.JLabel();
        theYear = new javax.swing.JLabel();
        insertCapacity = new javax.swing.JTextField();
        insertEvent = new javax.swing.JTextField();
        selectDay = new javax.swing.JComboBox();
        selectMonth = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        submit = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        insertTime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        insertTime.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(insertTime);
        insertTime.setBounds(200, 130, 223, 23);

        theDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        theDate.setForeground(new java.awt.Color(255, 255, 51));
        theDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        theDate.setText("DD:");
        getContentPane().add(theDate);
        theDate.setBounds(170, 90, 25, 28);

        theTime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        theTime.setForeground(new java.awt.Color(255, 255, 51));
        theTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        theTime.setText("TIME:");
        getContentPane().add(theTime);
        theTime.setBounds(160, 120, 35, 28);

        theEvent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        theEvent.setForeground(new java.awt.Color(255, 255, 51));
        theEvent.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        theEvent.setText("EVENT:");
        getContentPane().add(theEvent);
        theEvent.setBounds(150, 170, 46, 28);

        theCapacity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        theCapacity.setForeground(new java.awt.Color(255, 255, 51));
        theCapacity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        theCapacity.setText("CAPACITY:");
        getContentPane().add(theCapacity);
        theCapacity.setBounds(130, 210, 67, 28);

        theMonth.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        theMonth.setForeground(new java.awt.Color(255, 255, 51));
        theMonth.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        theMonth.setText(" MM:");
        getContentPane().add(theMonth);
        theMonth.setBounds(250, 90, 29, 28);

        theYear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        theYear.setForeground(new java.awt.Color(255, 255, 51));
        theYear.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        theYear.setText("YY:");
        getContentPane().add(theYear);
        theYear.setBounds(370, 90, 21, 28);

        insertCapacity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(insertCapacity);
        insertCapacity.setBounds(200, 210, 223, 23);

        insertEvent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        insertEvent.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(insertEvent);
        insertEvent.setBounds(200, 170, 223, 23);

        selectDay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        selectDay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(selectDay);
        selectDay.setBounds(200, 90, 44, 23);

        selectMonth.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        selectMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jan", "Feb", "March", "April", "May", "June", "July ", "Aug", "Sept", "Oct", "Nov", "Dec" }));
        getContentPane().add(selectMonth);
        selectMonth.setBounds(290, 90, 65, 23);

        jComboBox3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(400, 90, 70, 23);

        submit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        submit.setText("SUBMIT");
        getContentPane().add(submit);
        submit.setBounds(380, 270, 79, 25);

        back.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        back.setText("BACK");
        getContentPane().add(back);
        back.setBounds(140, 270, 65, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyBookingApp/olesereni2.jpeg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1, 0, 810, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(oleSereni1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(oleSereni1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(oleSereni1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(oleSereni1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new oleSereni1().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextField insertCapacity;
    private javax.swing.JTextField insertEvent;
    private javax.swing.JTextField insertTime;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox selectDay;
    private javax.swing.JComboBox selectMonth;
    private javax.swing.JButton submit;
    private javax.swing.JLabel theCapacity;
    private javax.swing.JLabel theDate;
    private javax.swing.JLabel theEvent;
    private javax.swing.JLabel theMonth;
    private javax.swing.JLabel theTime;
    private javax.swing.JLabel theYear;
    // End of variables declaration//GEN-END:variables
}
